version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build_test_frontend:
    working_directory: ~/project/www
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Build app
          command: | 
            npm install
            npm run build
      - run:
          name: Run tests
          command: npm run test
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_test_frontend
